version: '2'
services:
  odoo:
    build: .
#    image: odoo:12.0
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./extra-addons:/mnt/extra-addons
  
  db:
    image: postgres:9.5
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      